vehicule_homepage:
    path:     /
    defaults: { _controller: VehiculeBundle:Default:index }
vehicule_add:
    path:     /add
    defaults: { _controller: VehiculeBundle:Vehicule:add }
vehicule_list:
    path:     /list
    defaults: { _controller: VehiculeBundle:Vehicule:listVehicule }
vehicule_delete:
    path:     /delete/{id}
    defaults: { _controller: VehiculeBundle:Vehicule:delete }
vehicule_update:
    path:     /update/{id}
    defaults: { _controller: VehiculeBundle:Vehicule:update }
