vehicule_homepage:
    path:     /
    defaults: { _controller: VehiculeBundle:Default:index }
vehicule_add:
    path:     /add
    defaults: { _controller: VehiculeBundle:Vehicule:add }
vehicule_list:
    path:     /list
    defaults: { _controller: VehiculeBundle:Vehicule:listVehicule }
