taxi_homepage:
    path:     /
    defaults: { _controller: TaxiBundle:Default:index }

ajout_reservation_taxi:
    path:   /ajout
    defaults: { _controller: TaxiBundle:Default:ajout }

taxi_modifier:
    path:   /modifier/{id}
    defaults: { _controller: TaxiBundle:Default:modifier }
