taxi_homepage:
    path:     /
    defaults: { _controller: TaxiBundle:Default:index }

entities_reservation:
    resource: "@TransportBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation