taxi_homepage:
    path:     /
    defaults: { _controller: TaxiBundle:Default:index }

ajout_reservation_taxi:
    path:   /ajout
    defaults: { _controller: TaxiBundle:Default:ajout }

taxi_modifier:
    path:   /modifier/{id}
    defaults: { _controller: TaxiBundle:Default:modifier }

taxi_show:
    path:     /{id}/show
    defaults: { _controller: TaxiBundle:Default:show }
    methods:  GET

taxi_delete:
    path:     /{id}/delete
    defaults: { _controller: TaxiBundle:Default:delete }
    methods:  DELETE
