note_homepage:
    path:     /
    defaults: { _controller: NoteBundle:Default:index }
note_add:
    path:     /add
    defaults: { _controller: NoteBundle:Note:add }
note_list:
    path:     /list
    defaults: { _controller: NoteBundle:Note:list }

note_delete:
    path:     /delete/{id}
    defaults: { _controller: NoteBundle:Note:delete }
note_update:
    path:     /update/{id}
    defaults: { _controller: NoteBundle:Note:update }



