<?php

namespace EntitiesBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIdAdmin($idFos)
    {
        $qb = $this->getEntityManager()->
        createQuery("select a from EntitiesBundles:Admin a JOIN a.idFOS u WHERE u.id=:idO")
            ->setParameter('idO', $idFos);

        return $query = $qb->getResult();
    }
}