<?php

namespace EntitiesBundle\Repository;

/**
 * ChauffeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChauffeurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIdChauffeur($idFos)
    {
        $qb = $this->getEntityManager()->
        createQuery("select c from EntitiesBundles:Chauffeur c JOIN c.idFOS u WHERE u.id=:idO")
            ->setParameter('idO', $idFos);

        return $query = $qb->getResult();
    }
}