<?php

namespace EntitiesBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIdClient($idFos)
    {
        $qb = $this->getEntityManager()->
        createQuery("select c from EntitiesBundle:Client c JOIN c.idFOS u WHERE u.id= :idO")
            ->setParameter('idO', $idFos);

        return $query = $qb->getResult();
    }

    public function checkLoginMobile($mail,$pw)
    {
        $qb = $this->getEntityManager()
            ->createQuery("select c,u from EntitiesBundle:Client c JOIN c.idFOS u WHERE u.username = :mail")
            ->setParameter('mail', $mail);

        return $query = $qb->getResult();
    }
}
