<?php

namespace EntitiesBundle\Repository;

/**
 * GarageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GarageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getVehiculeGarage($immatriculation)
    {
        $qb = $this->getEntityManager()
            ->createQuery("select v from EntitiesBundle:Vehicule v where v.immatriculation = :imm")
            ->setParameter('imm',$immatriculation);

        return $query = $qb->getResult();
    }
}
