<?php

namespace EntitiesBundle\Repository;

/**
 * TheemesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TheemesRepository extends \Doctrine\ORM\EntityRepository
{


}
