back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /Back

taxi:
    resource: "@TaxiBundle/Resources/config/routing.yml"
    prefix:   /taxi

transport:
    resource: "@TransportBundle/Resources/config/routing.yml"
    prefix:   /transport

vehicule:
    resource: "@VehiculeBundle/Resources/config/routing.yml"
    prefix:   /vehicule


entities:
    resource: "@EntitiesBundle/Resources/config/routing.yml"
    prefix:   /entities

covoiturage:
    resource: "@CovoiturageBundle/Resources/config/routing.yml"
    prefix:   /covoiturage

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"