formation:
    resource: "@FormationBundle/Resources/config/routing.yml"
    prefix:   /formation

back:
  resource: "@BackBundle/Resources/config/routing.yml"
  prefix:   /Back

type:
  resource: "@TypeBundle/Resources/config/routing.yml"
  prefix:   /

inscriptions_covoiturage:
  resource: "@InscriptionsCovoiturageBundle/Resources/config/routing.yml"
  prefix:   /InscriptionsCovoiturage
garage:
  resource: "@GarageBundle/Resources/config/routing.yml"
  prefix:   /garage

taxi:
  resource: "@TaxiBundle/Resources/config/routing.yml"
  prefix:   /taxi
note:
  resource: "@NoteBundle/Resources/config/routing.yml"
  prefix:   /note
reclamation:
  resource: "@ReclamationBundle/Resources/config/routing.yml"
  prefix:   /reclamation

transport:
  resource: "@TransportBundle/Resources/config/routing.yml"
  prefix:   /transport

vehicule:
    resource: "@VehiculeBundle/Resources/config/routing.yml"
    prefix:   /vehicule


entities:
    resource: "@EntitiesBundle/Resources/config/routing.yml"
    prefix:   /entities

covoiturage:
    resource: "@CovoiturageBundle/Resources/config/routing.yml"
    prefix:   /covoiturage

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }
fp_js_form_validator:
    resource: "@FpJsFormValidatorBundle/Resources/config/routing.xml"
    prefix: /fp_js_form_validator