covoiturage_homepage:
    path:     /
    defaults: { _controller: CovoiturageBundle:Default:index }
covoiturage_ajout:
    path:     /ajout
    defaults: { _controller: CovoiturageBundle:Covoiturage:Ajout }
covoiturage_modifier:
    path:     /modifier/{offree}/{i}
    defaults: { _controller: CovoiturageBundle:Covoiturage:Modifier }
covoiturage_liste:
    path:     /liste
    defaults: { _controller: CovoiturageBundle:Covoiturage:Read }
covoiturage_supprimer:
    path:     /supprimer/{id}/{i}
    defaults: { _controller: CovoiturageBundle:Covoiturage:Supprimer }
covoiturage_statistiques:
    path:     /statistiques
    defaults: { _controller: CovoiturageBundle:Covoiturage:Statistiques }
covoiturage_erreur:
    path:     /erreur
    defaults: { _controller: CovoiturageBundle:Covoiturage:Erreur }
covoiturage_bloquer:
    path:     /bloquer/{offree}
    defaults: { _controller: CovoiturageBundle:Covoiturage:setAvertissement }
covoiturage_bloquer_delete:
    path:     /bloquerE/{id}
    defaults: { _controller: CovoiturageBundle:Covoiturage:setAvertissementDelete }
