<?php

namespace TransportBundle\Repository;

/**
 * quantiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class quantiteRepository extends \Doctrine\ORM\EntityRepository
{
}
