<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAlxpurs\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAlxpurs/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAlxpurs.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAlxpurs\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAlxpurs\appDevDebugProjectContainer([
    'container.build_hash' => 'Alxpurs',
    'container.build_id' => 'f428e60e',
    'container.build_time' => 1586978623,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAlxpurs');
