<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6c4dcu4\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6c4dcu4/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6c4dcu4.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6c4dcu4\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6c4dcu4\appDevDebugProjectContainer([
    'container.build_hash' => '6c4dcu4',
    'container.build_id' => 'aa4c80ec',
    'container.build_time' => 1587137136,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6c4dcu4');
